# -*- coding: utf-8 -*-
"""ex calculadora de imposto de renda e inss

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ML3iaQjctdmcrfvBBeOxgKA_pmafyoU
"""

hora = float(input('quantas horas por mes vc trabalha?'))
valor_hora = float(input('quanto voce recebe por hora?'))
salario = hora * valor_hora
print('seu salario bruto é:' , salario)

if salario <= 1903.98:
  print('sem imposto de renda')
  impostorenda = 0
elif salario >= 1903.99 and salario <= 2826.65:
  print('a porcentagem do ir é de 7,5%')
  impostorenda = 0.075
  valor_ir = 142.80
elif salario >= 2826.66 and salario <= 3751.05:
  print('a porcentagem do ir é de 15%')
  impostorenda = 0.15
  valor_ir = 354.80
elif salario >= 3751.06 and salario <= 4664.68:
   print('a porcentagem do ir é de 22.5%')
   impostorenda = 0.225
   valor_ir = 636,13
else:
    print('a porcentagem do ir é de 27.5%')
    impostorenda = 0.275

valor_ir = salario * impostorenda
if valor_ir >= 869.36:
  valor_ir = 869.36
print('o valor do imposto de renda é:' , valor_ir)

if salario <= 1302:
  print('a porcentagem do inss é de 7.5% e o valor é de:' , salario * 0.075)
  valorinss = 0.075
elif salario > 1302 and salario <= 2571.29:
  print('a porcentagem do inss é de 9% e o valor é de:' , salario * 0.09)
  valorinss = 0.09
elif salario > 2571.30 and salario <= 3856.94:
  print('a porcentagem do inss é de 12% e o valor é de:' , salario * 0.12)
  valorinss = 0.12
elif salario > 3856.95 and salario <= 7507.49:
  print('a porcentagem do inss é de 14% e o valor é de:' , salario * 0.14)
  valorinss = 0.14

valor_inss  =  salario * (float(valorinss))

salario_liquido = salario - (valor_inss + valor_ir)
print('seu salario com o valor do imposto é:' , salario_liquido)